services:
  app:
    image: node:24-slim
    container_name: queue-appointment-system-app
    ports:
      - "127.0.0.1:3000:3000"
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm install && npm run dev"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=${REDIS_URL}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: queue-appointment-system-redis
    ports:
      - "127.0.0.1:6379:6379"
